
#include "MicroJavaLexer.h"
#include "MicroJavaParser.h"

#define INDENT_INC 2

const ANTLR3_UINT32 special_tokens[] = {PROGRAM, DEF, IF, WHILE};
const int SPECIAL_SIZE = sizeof(special_tokens) / sizeof(ANTLR3_UINT32);

void _pp_special(pANTLR3_BASE_TREE node, int indent);

bool isSpecial(pANTLR3_BASE_TREE node) {
    pANTLR3_COMMON_TOKEN token = node->getToken(node);
    ANTLR3_UINT32 type = token->getType(token);
    for (int i = 0; i < SPECIAL_SIZE; i++) {
        if (special_tokens[i] == type) {
            return true;
        }
    }

    return false;
}

void _pp(pANTLR3_BASE_TREE node, int indent) {

    if (isSpecial(node)) {
        _pp_special(node, indent);
        return;
    }

    pANTLR3_COMMON_TOKEN token = node->getToken(node);

    int childCount = node->getChildCount(node);
    if (node->isNilNode(node) == ANTLR3_FALSE
            && childCount > 0) {
        printf(" (");
    } else {
        printf(" ");
    }

    printf("%s", token->getText(token)->chars);

    for(int i = 0; i < childCount; i++) {
        _pp((pANTLR3_BASE_TREE)node->getChild(node, i), indent);
    }

    if (node->isNilNode(node) == ANTLR3_FALSE
            && childCount > 0) {
        printf(")");
    }

}

void _indent(int ammount) {
    printf("\n");
    for (int i = 0; i < ammount; i++) {
        printf(" ");
    }
}

void _pp_special(pANTLR3_BASE_TREE node, int indent) {
    _indent(indent);

    printf("(%s", node->getText(node)->chars);
    int childCount = node->getChildCount(node);
    if (childCount > 0) {
        _pp((pANTLR3_BASE_TREE)node->getChild(node, 0), indent + 2* INDENT_INC);
    }

    int newIndent = indent + INDENT_INC;
    for (int i = 1; i < childCount; i++) {
        _indent(newIndent);
        _pp((pANTLR3_BASE_TREE)node->getChild(node, i), newIndent);
    }

    printf(")");

}

void pp(pANTLR3_BASE_TREE root) {
    _pp(root, 0);
}

int main(int argc, char** argv) {

    const char *filename = (argc < 2 || argv[1] == NULL)?
                        "./input" : argv[1];

    pANTLR3_UINT8                   fName = (pANTLR3_UINT8)filename;
    pANTLR3_INPUT_STREAM            input;
    pMicroJavaLexer                 lxr;
    pANTLR3_COMMON_TOKEN_STREAM     tstream;
    
    pMicroJavaParser                psr;
    MicroJavaParser_program_return  langAST;

    input	= antlr3AsciiFileStreamNew(fName);

    if (input == NULL)
    {
        fprintf(stderr, "Unable to open file %s\n", (char *)fName);
        exit(ANTLR3_ERR_NOMEM);
    }

    lxr	    = MicroJavaLexerNew(input);	    // CLexerNew is generated by ANTLR

    if ( lxr == NULL )
    {
        fprintf(stderr, "Unable to create the lexer due to malloc() failure1\n");
        exit(ANTLR3_ERR_NOMEM);
    }

    tstream = antlr3CommonTokenStreamSourceNew(ANTLR3_SIZE_HINT, TOKENSOURCE(lxr));

    if (tstream == NULL)
    {
        fprintf(stderr, "Out of memory trying to allocate token stream\n");
        exit(ANTLR3_ERR_NOMEM);
    }

    psr	    = MicroJavaParserNew(tstream);  // CParserNew is generated by ANTLR3

    if (psr == NULL)
    {
        fprintf(stderr, "Out of memory trying to allocate parser\n");
        exit(ANTLR3_ERR_NOMEM);
    }
    
    langAST = psr->program(psr);

    if (psr->pParser->rec->state->errorCount > 0)
    {
        fprintf(stderr, "The parser returned %d errors, tree walking aborted.\n", psr->pParser->rec->state->errorCount);
        exit(1);
    }
    else
    {
        pp(langAST.tree);
    }

    psr	    ->free  (psr);		psr		= NULL;
    tstream ->free  (tstream);	tstream	= NULL;
    lxr	    ->free  (lxr);	    lxr		= NULL;
    input   ->close (input);	input	= NULL;

}

